<a href="https://colab.research.google.com/github/TemiDavid/blank-app/blob/main/Capstone_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Library

In [466]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [467]:
# import needed library
import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt

# Load and Inspect Data

In [468]:
# Read in data
df = pd.read_csv("/content/mine_files/financial_loan.csv")

# Create a copy to work on so that I can always have the source data
df_copy = df.copy()


In [469]:
# View first five row
df_copy.head()

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,INDIVIDUAL,< 1 year,Ryder,C,RENT,2/11/2021,9/13/2021,4/13/2021,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,INDIVIDUAL,9 years,MKC Accounting,E,RENT,1/1/2021,12/14/2021,1/15/2021,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,INDIVIDUAL,4 years,Chemat Technology Inc,C,RENT,1/5/2021,12/12/2021,1/9/2021,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
3,1041756,TX,INDIVIDUAL,< 1 year,barnes distribution,B,MORTGAGE,2/25/2021,12/12/2021,3/12/2021,...,B2,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911
4,1068350,IL,INDIVIDUAL,10+ years,J&J Steel Inc,A,MORTGAGE,1/1/2021,12/14/2021,1/15/2021,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835


In [470]:
# View last five row
df_copy.tail()

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
38571,803452,NJ,INDIVIDUAL,< 1 year,Joseph M Sanzari Company,C,MORTGAGE,7/11/2021,5/16/2021,5/16/2021,...,C1,60 months,Verified,100000.0,0.1986,551.64,0.1299,24250,33,31946
38572,970377,NY,INDIVIDUAL,8 years,Swat Fame,C,RENT,10/11/2021,4/16/2021,5/16/2021,...,C1,60 months,Verified,50000.0,0.0458,579.72,0.1349,25200,18,31870
38573,875376,CA,INDIVIDUAL,5 years,Anaheim Regional Medical Center,D,RENT,9/11/2021,5/16/2021,5/16/2021,...,D5,60 months,Verified,65000.0,0.1734,627.93,0.1749,25000,20,35721
38574,972997,NY,INDIVIDUAL,5 years,Brooklyn Radiology,D,RENT,10/11/2021,5/16/2021,5/16/2021,...,D5,60 months,Verified,368000.0,0.0009,612.72,0.1825,24000,9,33677
38575,682952,NY,INDIVIDUAL,4 years,Allen Edmonds,F,RENT,7/11/2021,5/16/2021,5/16/2021,...,F3,60 months,Verified,80000.0,0.0600,486.86,0.2099,18000,7,27679


In [471]:
# Let's check the dimension
df_copy.shape

(38576, 24)

In [472]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38576 entries, 0 to 38575
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id                     38576 non-null  int64  
 1   address_state          38576 non-null  object 
 2   application_type       38576 non-null  object 
 3   emp_length             38576 non-null  object 
 4   emp_title              37138 non-null  object 
 5   grade                  38576 non-null  object 
 6   home_ownership         38576 non-null  object 
 7   issue_date             38576 non-null  object 
 8   last_credit_pull_date  38576 non-null  object 
 9   last_payment_date      38576 non-null  object 
 10  loan_status            38576 non-null  object 
 11  next_payment_date      38576 non-null  object 
 12  member_id              38576 non-null  int64  
 13  purpose                38576 non-null  object 
 14  sub_grade              38576 non-null  object 
 15  te

In [473]:
df_copy.describe(include="all")

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
count,3.857600e+04,38576,38576,38576,37138,38576,38576,38576,38576,38576,...,38576,38576,38576,3.857600e+04,38576.000000,38576.000000,38576.000000,38576.000000,38576.000000,38576.000000
unique,NaN,50,1,11,28525,7,5,65,107,102,...,35,2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,CA,INDIVIDUAL,10+ years,US Army,B,RENT,12/11/2021,5/16/2021,5/16/2021,...,B3,36 months,Not Verified,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,6894,38576,8870,135,11674,18439,2188,10041,1209,...,2834,28237,16464,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,6.810371e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,6.964454e+04,0.133274,326.862965,0.120488,11296.066855,22.132544,12263.348533
std,2.113246e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,6.429368e+04,0.066662,209.092000,0.037164,7460.746022,11.392282,9051.104777
min,5.473400e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4.000000e+03,0.000000,15.690000,0.054200,500.000000,2.000000,34.000000
25%,5.135170e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4.150000e+04,0.082100,168.450000,0.093200,5500.000000,14.000000,5633.000000
50%,6.627280e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,6.000000e+04,0.134200,283.045000,0.118600,10000.000000,20.000000,10042.000000
75%,8.365060e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,8.320050e+04,0.185900,434.442500,0.145900,15000.000000,29.000000,16658.000000


# To Clean Data

* Removal of unrequired features

In [474]:
# Removal of features that should not be used since they do not help predict creditworthiness for a new application.

df_copy = df_copy.drop("id", axis=1) # Exclude id since its an identifier alone and not predictive

df_copy = df_copy.drop("address_state", axis=1) # Exclude id since its an identifier alone and not predictive

df_copy = df_copy.drop("emp_title", axis=1) # Exclude since this is an identifier alone

df_copy = df_copy.drop("next_payment_date", axis=1) # Exclude since its a future information

df_copy = df_copy.drop("total_payment", axis=1) # Exclude since its just an outcome after a loan

df_copy = df_copy.drop("member_id", axis=1) # Exclude since its an identifier alone and not predictive

df_copy = df_copy.drop("application_type", axis=1) # Exclude since we have just an application type






In [475]:
df_copy.describe(include="all")

,emp_length,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,loan_status,purpose,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc
count,38576,38576,38576,38576,38576,38576,38576,38576,38576,38576,38576,3.857600e+04,38576.000000,38576.000000,38576.000000,38576.000000,38576.000000
unique,11,7,5,65,107,102,3,14,35,2,3,NaN,NaN,NaN,NaN,NaN,NaN
top,10+ years,B,RENT,12/11/2021,5/16/2021,5/16/2021,Fully Paid,Debt consolidation,B3,36 months,Not Verified,NaN,NaN,NaN,NaN,NaN,NaN
freq,8870,11674,18439,2188,10041,1209,32145,18214,2834,28237,16464,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.964454e+04,0.133274,326.862965,0.120488,11296.066855,22.132544
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.429368e+04,0.066662,209.092000,0.037164,7460.746022,11.392282
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000e+03,0.000000,15.690000,0.054200,500.000000,2.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.150000e+04,0.082100,168.450000,0.093200,5500.000000,14.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000e+04,0.134200,283.045000,0.118600,10000.000000,20.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.320050e+04,0.185900,434.442500,0.145900,15000.000000,29.000000


In [476]:
# Let's check the dimension
df_copy.shape

(38576, 17)

In [477]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38576 entries, 0 to 38575
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   emp_length             38576 non-null  object 
 1   grade                  38576 non-null  object 
 2   home_ownership         38576 non-null  object 
 3   issue_date             38576 non-null  object 
 4   last_credit_pull_date  38576 non-null  object 
 5   last_payment_date      38576 non-null  object 
 6   loan_status            38576 non-null  object 
 7   purpose                38576 non-null  object 
 8   sub_grade              38576 non-null  object 
 9   term                   38576 non-null  object 
 10  verification_status    38576 non-null  object 
 11  annual_income          38576 non-null  float64
 12  dti                    38576 non-null  float64
 13  installment            38576 non-null  float64
 14  int_rate               38576 non-null  float64
 15  lo

### Check unique values to determine and fix inconsistencies

* Check for emp_length

In [478]:
# Check unique values in emp_length column
df_copy["emp_length"].unique()

array(['< 1 year', '9 years', '4 years', '10+ years', '3 years',
       '5 years', '1 year', '6 years', '2 years', '7 years', '8 years'],
      dtype=object)

In [479]:
# Let's remove the "years" at the back of the emp_length
df_copy["emp_length"] = df_copy[ "emp_length"].str.replace('year', '', regex=False)

In [480]:
# Let's remove the "s" at the back of the emp_length
df_copy["emp_length"] = df_copy[ "emp_length"].str.replace('s', '', regex=False)

In [481]:
# Let's see unique value again
df_copy["emp_length"].unique()

array(['< 1 ', '9 ', '4 ', '10+ ', '3 ', '5 ', '1 ', '6 ', '2 ', '7 ',
       '8 '], dtype=object)

In [482]:
# Check unique values in grade column
df_copy["grade"].unique()

array(['C', 'E', 'B', 'A', 'D', 'F', 'G'], dtype=object)

In [483]:
# Check unique values in home_ownership column
df_copy["home_ownership"].unique()

array(['RENT', 'MORTGAGE', 'OWN', 'OTHER', 'NONE'], dtype=object)

In [484]:
# Check unique values in issue_date column
df_copy["issue_date"].unique()

array(['2/11/2021', '1/1/2021', '1/5/2021', '2/25/2021', '7/17/2021',
       '11/19/2021', '6/11/2021', '9/2/2021', '2/9/2021', '7/22/2021',
       '9/11/2021', '8/11/2021', '12/11/2021', '10/11/2021', '12/2/2021',
       '10/9/2021', '12/12/2021', '2/2/2021', '7/7/2021', '1/8/2021',
       '8/9/2021', '1/11/2021', '11/11/2021', '6/9/2021', '1/10/2021',
       '5/11/2021', '3/10/2021', '5/10/2021', '5/9/2021', '4/11/2021',
       '7/9/2021', '12/9/2021', '11/9/2021', '3/9/2021', '10/8/2021',
       '3/8/2021', '11/8/2021', '9/7/2021', '2/8/2021', '8/7/2021',
       '1/9/2021', '12/10/2021', '3/11/2021', '7/10/2021', '7/11/2021',
       '4/9/2021', '2/10/2021', '8/10/2021', '4/10/2021', '11/10/2021',
       '10/10/2021', '6/10/2021', '9/9/2021', '8/8/2021', '9/10/2021',
       '12/8/2021', '5/8/2021', '6/8/2021', '9/8/2021', '7/8/2021',
       '4/8/2021', '11/7/2021', '10/7/2021', '12/7/2021', '6/7/2021'],
      dtype=object)

In [485]:
# Convert Join_Date to datetime
def parse_date(value):
    """
    A function that handles any data format
    present in the issue_date column
    """
    # If already a datetime, return it
    if isinstance(value, pd.Timestamp):
        return value

    # Handle missing values
    if pd.isna(value):
        return pd.NaT

    # Try parsing string dates
    value = str(value).strip()

    for fmt in ("%Y-%m-%d", "%d-%m-%Y", "%Y/%m/%d", "%m/%d/%Y"):
        try:
            return datetime.strptime(value, fmt)
        except ValueError:
            continue

    # If all parsing fails
    return pd.NaT

# Let's call in the function on the Join_Date column
df_copy["issue_date"] = df_copy["issue_date"].apply(parse_date)

In [486]:
# Check unique values in issue_date column
df_copy["issue_date"].unique()

<DatetimeArray>
['2021-02-11 00:00:00', '2021-01-01 00:00:00', '2021-01-05 00:00:00',
 '2021-02-25 00:00:00', '2021-07-17 00:00:00', '2021-11-19 00:00:00',
 '2021-06-11 00:00:00', '2021-09-02 00:00:00', '2021-02-09 00:00:00',
 '2021-07-22 00:00:00', '2021-09-11 00:00:00', '2021-08-11 00:00:00',
 '2021-12-11 00:00:00', '2021-10-11 00:00:00', '2021-12-02 00:00:00',
 '2021-10-09 00:00:00', '2021-12-12 00:00:00', '2021-02-02 00:00:00',
 '2021-07-07 00:00:00', '2021-01-08 00:00:00', '2021-08-09 00:00:00',
 '2021-01-11 00:00:00', '2021-11-11 00:00:00', '2021-06-09 00:00:00',
 '2021-01-10 00:00:00', '2021-05-11 00:00:00', '2021-03-10 00:00:00',
 '2021-05-10 00:00:00', '2021-05-09 00:00:00', '2021-04-11 00:00:00',
 '2021-07-09 00:00:00', '2021-12-09 00:00:00', '2021-11-09 00:00:00',
 '2021-03-09 00:00:00', '2021-10-08 00:00:00', '2021-03-08 00:00:00',
 '2021-11-08 00:00:00', '2021-09-07 00:00:00', '2021-02-08 00:00:00',
 '2021-08-07 00:00:00', '2021-01-09 00:00:00', '2021-12-10 00:00:00',
 '20

In [487]:
# Check unique values in issue_date column
df_copy["last_credit_pull_date"].unique()

array(['9/13/2021', '12/14/2021', '12/12/2021', '3/16/2021', '6/14/2021',
       '7/14/2021', '6/15/2021', '3/13/2021', '10/13/2021', '2/14/2021',
       '4/16/2021', '9/15/2021', '5/16/2021', '12/9/2021', '2/13/2021',
       '11/13/2021', '11/10/2021', '4/14/2021', '1/12/2021', '3/12/2021',
       '6/11/2021', '12/13/2021', '6/12/2021', '3/14/2021', '4/11/2021',
       '11/11/2021', '2/15/2021', '7/11/2021', '12/10/2021', '1/11/2021',
       '8/7/2021', '5/10/2021', '9/12/2021', '9/10/2021', '2/10/2021',
       '3/11/2021', '2/16/2021', '5/12/2021', '2/11/2021', '10/14/2021',
       '1/14/2021', '9/11/2021', '11/14/2021', '9/14/2021', '12/15/2021',
       '11/12/2021', '11/15/2021', '8/14/2021', '7/15/2021', '12/11/2021',
       '10/15/2021', '8/13/2021', '3/10/2021', '8/11/2021', '1/16/2021',
       '7/13/2021', '4/13/2021', '5/14/2021', '5/13/2021', '5/15/2021',
       '8/12/2021', '1/15/2021', '5/11/2021', '4/15/2021', '10/12/2021',
       '10/11/2021', '8/15/2021', '2/12/2021', '4

In [488]:
# Convert last_credit_pull_date to datetime
def parse_date(value):
    """
    A function that handles any data format
    present in the last_credit_pull_date
    """
    # If already a datetime, return it
    if isinstance(value, pd.Timestamp):
        return value

    # Handle missing values
    if pd.isna(value):
        return pd.NaT

    # Try parsing string dates
    value = str(value).strip()

    for fmt in ("%Y-%m-%d", "%d-%m-%Y", "%Y/%m/%d", "%m/%d/%Y"):
        try:
            return datetime.strptime(value, fmt)
        except ValueError:
            continue

    # If all parsing fails
    return pd.NaT

# Let's call in the function on the Join_Date column
df_copy["last_credit_pull_date"] = df_copy["last_credit_pull_date"].apply(parse_date)

In [489]:
# Check unique values in issue_date column
df_copy["last_credit_pull_date"].unique()

<DatetimeArray>
['2021-09-13 00:00:00', '2021-12-14 00:00:00', '2021-12-12 00:00:00',
 '2021-03-16 00:00:00', '2021-06-14 00:00:00', '2021-07-14 00:00:00',
 '2021-06-15 00:00:00', '2021-03-13 00:00:00', '2021-10-13 00:00:00',
 '2021-02-14 00:00:00',
 ...
 '2021-10-07 00:00:00', '2021-07-09 00:00:00', '2021-05-08 00:00:00',
 '2021-03-08 00:00:00', '2021-05-07 00:00:00', '2021-07-08 00:00:00',
 '2021-09-07 00:00:00', '2022-01-20 00:00:00', '2021-06-08 00:00:00',
 '2021-07-07 00:00:00']
Length: 107, dtype: datetime64[ns]

In [490]:
# Check unique values in issue_date column
df_copy["last_payment_date"].unique()

array(['4/13/2021', '1/15/2021', '1/9/2021', '3/12/2021', '8/12/2021',
       '12/13/2021', '7/14/2021', '10/12/2021', '3/16/2021', '8/13/2021',
       '9/13/2021', '12/14/2021', '10/13/2021', '11/12/2021', '2/15/2021',
       '8/10/2021', '2/10/2021', '6/11/2021', '8/8/2021', '6/13/2021',
       '12/9/2021', '2/12/2021', '7/12/2021', '7/10/2021', '1/13/2021',
       '8/11/2021', '10/11/2021', '1/11/2021', '7/13/2021', '10/9/2021',
       '11/13/2021', '11/10/2021', '3/11/2021', '7/11/2021', '6/12/2021',
       '12/11/2021', '9/9/2021', '5/13/2021', '3/14/2021', '4/8/2021',
       '10/10/2021', '5/10/2021', '2/11/2021', '9/10/2021', '4/10/2021',
       '6/10/2021', '5/12/2021', '10/14/2021', '6/14/2021', '5/14/2021',
       '1/14/2021', '4/14/2021', '9/11/2021', '8/14/2021', '11/14/2021',
       '1/12/2021', '2/14/2021', '12/12/2021', '4/12/2021', '2/13/2021',
       '9/14/2021', '3/10/2021', '11/11/2021', '4/11/2021', '3/13/2021',
       '5/11/2021', '11/9/2021', '9/12/2021', '2/9/202

In [491]:
# Convert last_payment_date to datetime
def parse_date(value):
    """
    A function that handles any data format
    present in the last_credit_pull_date
    """
    # If already a datetime, return it
    if isinstance(value, pd.Timestamp):
        return value

    # Handle missing values
    if pd.isna(value):
        return pd.NaT

    # Try parsing string dates
    value = str(value).strip()

    for fmt in ("%Y-%m-%d", "%d-%m-%Y", "%Y/%m/%d", "%m/%d/%Y"):
        try:
            return datetime.strptime(value, fmt)
        except ValueError:
            continue

    # If all parsing fails
    return pd.NaT

# Let's call in the function on the Join_Date column
df_copy["last_payment_date"] = df_copy["last_payment_date"].apply(parse_date)

In [492]:
# Check unique values in issue_date column
df_copy["last_payment_date"].unique()

<DatetimeArray>
['2021-04-13 00:00:00', '2021-01-15 00:00:00', '2021-01-09 00:00:00',
 '2021-03-12 00:00:00', '2021-08-12 00:00:00', '2021-12-13 00:00:00',
 '2021-07-14 00:00:00', '2021-10-12 00:00:00', '2021-03-16 00:00:00',
 '2021-08-13 00:00:00',
 ...
 '2021-04-09 00:00:00', '2021-05-08 00:00:00', '2021-03-09 00:00:00',
 '2021-09-08 00:00:00', '2021-11-08 00:00:00', '2021-07-08 00:00:00',
 '2021-06-08 00:00:00', '2021-03-08 00:00:00', '2021-02-08 00:00:00',
 '2021-01-08 00:00:00']
Length: 102, dtype: datetime64[ns]

In [493]:
# Check unique values in issue_date column
df_copy["purpose"].unique()

array(['car', 'credit card', 'Debt consolidation', 'educational',
       'home improvement', 'house', 'major purchase', 'medical', 'moving',
       'other', 'renewable_energy', 'small business', 'vacation',
       'wedding'], dtype=object)

In [494]:
# Check unique values in issue_date column
df_copy["sub_grade"].unique()

array(['C4', 'E1', 'C5', 'B2', 'A1', 'C3', 'C2', 'A4', 'A5', 'B5', 'B4',
       'B3', 'B1', 'D1', 'A2', 'A3', 'D4', 'D2', 'C1', 'D3', 'E3', 'F1',
       'E2', 'E5', 'D5', 'E4', 'F2', 'G3', 'F3', 'G1', 'F4', 'G4', 'G2',
       'F5', 'G5'], dtype=object)

In [495]:
# Check unique values in issue_date column
df_copy["term"].unique()

array([' 60 months', ' 36 months'], dtype=object)

In [496]:
# Check unique values in issue_date column
df_copy["verification_status"].unique()

array(['Source Verified', 'Not Verified', 'Verified'], dtype=object)

In [497]:
# Check unique values in issue_date column
df_copy["annual_income"].unique()

array([ 30000. ,  48000. ,  50000. , ...,  44250. ,  57040.5, 368000. ])

In [498]:
# Check unique values in issue_date column
df_copy["dti"].unique()

array([0.01  , 0.0535, 0.2088, ..., 0.2721, 0.2543, 0.272 ])

In [499]:
# Check unique values in issue_date column
df_copy["installment"].unique()

array([ 59.83, 109.43, 421.65, ..., 164.99, 113.5 , 627.93])

In [500]:
# Check unique values in issue_date column
df_copy["int_rate"].unique()

array([0.1527, 0.1864, 0.1596, 0.1065, 0.0603, 0.1465, 0.1427, 0.079 ,
       0.089 , 0.1269, 0.1242, 0.1171, 0.0991, 0.1629, 0.0743, 0.1114,
       0.1109, 0.0766, 0.0751, 0.0963, 0.0894, 0.1148, 0.1149, 0.157 ,
       0.0788, 0.0705, 0.1189, 0.1074, 0.1284, 0.0749, 0.0849, 0.1136,
       0.1199, 0.1095, 0.1099, 0.1221, 0.1241, 0.1134, 0.1399, 0.1367,
       0.1677, 0.1   , 0.0807, 0.0863, 0.0976, 0.1393, 0.0712, 0.1046,
       0.092 , 0.1166, 0.1091, 0.1103, 0.074 , 0.0768, 0.0662, 0.0599,
       0.0699, 0.0729, 0.0542, 0.0676, 0.0774, 0.0692, 0.0932, 0.0617,
       0.0639, 0.0579, 0.08  , 0.0859, 0.0714, 0.0691, 0.0737, 0.0832,
       0.0925, 0.1075, 0.0999, 0.1036, 0.1025, 0.1111, 0.1126, 0.1218,
       0.1059, 0.0962, 0.1037, 0.1158, 0.0988, 0.1062, 0.1253, 0.1051,
       0.1287, 0.1273, 0.138 , 0.1472, 0.1347, 0.1523, 0.1426, 0.1268,
       0.1311, 0.1417, 0.1349, 0.1304, 0.1599, 0.1595, 0.1533, 0.0654,
       0.1183, 0.1357, 0.1306, 0.1422, 0.1316, 0.1496, 0.1565, 0.1474,
      

In [501]:
# Check unique values in issue_date column
df_copy["loan_amount"].unique()

array([ 2500,  3000, 12000,  4500,  3500,  8000,  6000,  5500, 24000,
        4125,  5400, 11200,  5000,  3050, 10000,  2225,  4000,  7000,
        9000,  4800,  6300,  4750,  1850,  4200,  7200,  2400,  7500,
        5550, 22000,  3200, 11000,  4400,  8500,  2000,  7400,  5650,
        1800,  6500, 15000,  8700,  5600,  4600,  3800, 16000,  1300,
        7800,  5900,  3600,  2100,  4975,  1925,  1500,  7750,  9600,
        3900, 12975,  5950,  5100,  5200,  1200,  4650,  1450,  3250,
        3300,  1700,  5525, 18000,  1750,  5375,  9500,  7600,  6400,
        9900,  1000, 10400, 23500, 22600, 23600, 13100,  5800, 10800,
        1900,  8400,  3075,  6200, 11500,  4350,  4150,  4900,  6125,
        2425,  1600,  7100,  8900, 14000, 12250,  3700, 17000,  2550,
        6250, 14400,  8200,  9250,  3375,  1675,  8600,  2800,  3525,
        8800,  2250,  4375,  1275,  5050, 25000,  9800,  6600,  8250,
        2825,  5975,  3350, 20000, 19000,  2200, 14750,  9575, 13250,
        2350, 10625,

In [502]:
# Check unique values in issue_date column
df_copy["total_acc"].unique()

array([ 4, 11,  9, 28, 30, 23, 31, 21, 33, 13,  3, 15, 18, 14,  8,  7, 20,
       39, 24, 10, 19, 27,  6, 16, 45, 25,  5, 43, 29, 22, 41, 35, 44, 36,
       17, 26, 37, 32, 47, 52, 42, 46, 12, 50, 34, 59, 38, 63, 49, 48, 61,
       51, 55, 40, 53, 62, 58, 67, 54, 57, 56, 70,  2, 64, 60, 80, 79, 71,
       66, 65, 69, 90, 68, 74, 75, 87, 78, 72, 77, 81, 76, 73])

* Fix Data Types

In [503]:
# Convert emp_length
df_copy['emp_length'] = pd.to_numeric(df_copy['emp_length'], errors='coerce')


In [504]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38576 entries, 0 to 38575
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   emp_length             25131 non-null  float64       
 1   grade                  38576 non-null  object        
 2   home_ownership         38576 non-null  object        
 3   issue_date             38576 non-null  datetime64[ns]
 4   last_credit_pull_date  38576 non-null  datetime64[ns]
 5   last_payment_date      38576 non-null  datetime64[ns]
 6   loan_status            38576 non-null  object        
 7   purpose                38576 non-null  object        
 8   sub_grade              38576 non-null  object        
 9   term                   38576 non-null  object        
 10  verification_status    38576 non-null  object        
 11  annual_income          38576 non-null  float64       
 12  dti                    38576 non-null  float64       
 13  i