<a href="https://colab.research.google.com/github/TemiDavid/blank-app/blob/main/Capstone_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Library

In [80]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [81]:
# import needed library
import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt

# Load and Inspect Data

In [82]:
# Read in data
df = pd.read_csv("/content/mine_files/financial_loan.csv")

# Create a copy to work on so that I can always have the source data
df_copy = df.copy()


In [83]:
# View first five row
df_copy.head()

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,INDIVIDUAL,< 1 year,Ryder,C,RENT,2/11/2021,9/13/2021,4/13/2021,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,INDIVIDUAL,9 years,MKC Accounting,E,RENT,1/1/2021,12/14/2021,1/15/2021,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,INDIVIDUAL,4 years,Chemat Technology Inc,C,RENT,1/5/2021,12/12/2021,1/9/2021,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
3,1041756,TX,INDIVIDUAL,< 1 year,barnes distribution,B,MORTGAGE,2/25/2021,12/12/2021,3/12/2021,...,B2,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911
4,1068350,IL,INDIVIDUAL,10+ years,J&J Steel Inc,A,MORTGAGE,1/1/2021,12/14/2021,1/15/2021,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835


In [84]:
# View last five row
df_copy.tail()

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
38571,803452,NJ,INDIVIDUAL,< 1 year,Joseph M Sanzari Company,C,MORTGAGE,7/11/2021,5/16/2021,5/16/2021,...,C1,60 months,Verified,100000.0,0.1986,551.64,0.1299,24250,33,31946
38572,970377,NY,INDIVIDUAL,8 years,Swat Fame,C,RENT,10/11/2021,4/16/2021,5/16/2021,...,C1,60 months,Verified,50000.0,0.0458,579.72,0.1349,25200,18,31870
38573,875376,CA,INDIVIDUAL,5 years,Anaheim Regional Medical Center,D,RENT,9/11/2021,5/16/2021,5/16/2021,...,D5,60 months,Verified,65000.0,0.1734,627.93,0.1749,25000,20,35721
38574,972997,NY,INDIVIDUAL,5 years,Brooklyn Radiology,D,RENT,10/11/2021,5/16/2021,5/16/2021,...,D5,60 months,Verified,368000.0,0.0009,612.72,0.1825,24000,9,33677
38575,682952,NY,INDIVIDUAL,4 years,Allen Edmonds,F,RENT,7/11/2021,5/16/2021,5/16/2021,...,F3,60 months,Verified,80000.0,0.0600,486.86,0.2099,18000,7,27679


In [85]:
# Let's check the dimension
df_copy.shape

(38576, 24)

In [86]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38576 entries, 0 to 38575
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id                     38576 non-null  int64  
 1   address_state          38576 non-null  object 
 2   application_type       38576 non-null  object 
 3   emp_length             38576 non-null  object 
 4   emp_title              37138 non-null  object 
 5   grade                  38576 non-null  object 
 6   home_ownership         38576 non-null  object 
 7   issue_date             38576 non-null  object 
 8   last_credit_pull_date  38576 non-null  object 
 9   last_payment_date      38576 non-null  object 
 10  loan_status            38576 non-null  object 
 11  next_payment_date      38576 non-null  object 
 12  member_id              38576 non-null  int64  
 13  purpose                38576 non-null  object 
 14  sub_grade              38576 non-null  object 
 15  te

In [87]:
df_copy.describe(include="all")

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
count,3.857600e+04,38576,38576,38576,37138,38576,38576,38576,38576,38576,...,38576,38576,38576,3.857600e+04,38576.000000,38576.000000,38576.000000,38576.000000,38576.000000,38576.000000
unique,NaN,50,1,11,28525,7,5,65,107,102,...,35,2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,CA,INDIVIDUAL,10+ years,US Army,B,RENT,12/11/2021,5/16/2021,5/16/2021,...,B3,36 months,Not Verified,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,6894,38576,8870,135,11674,18439,2188,10041,1209,...,2834,28237,16464,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,6.810371e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,6.964454e+04,0.133274,326.862965,0.120488,11296.066855,22.132544,12263.348533
std,2.113246e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,6.429368e+04,0.066662,209.092000,0.037164,7460.746022,11.392282,9051.104777
min,5.473400e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4.000000e+03,0.000000,15.690000,0.054200,500.000000,2.000000,34.000000
25%,5.135170e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4.150000e+04,0.082100,168.450000,0.093200,5500.000000,14.000000,5633.000000
50%,6.627280e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,6.000000e+04,0.134200,283.045000,0.118600,10000.000000,20.000000,10042.000000
75%,8.365060e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,8.320050e+04,0.185900,434.442500,0.145900,15000.000000,29.000000,16658.000000


# To Clean Data

* Removal of unrequired features

In [88]:
# Removal of features that should not be used since they do not help predict creditworthiness for a new application.

df_copy = df_copy.drop("id", axis=1) # Exclude id since its an identifier alone and not predictive
df_copy = df_copy.drop("address_state", axis=1) # Exclude id since its an identifier alone and not predictive
df_copy = df_copy.drop("emp_title", axis=1) # Exclude since this is an identifier alone
df_copy = df_copy.drop("grade", axis=1) # Exclude as this is not required
df_copy = df_copy.drop("issue_date", axis=1) # Exclude since this has no effect on the prediction
df_copy = df_copy.drop("last_credit_pull_date", axis=1) # Exclude happens after loan is issued
df_copy = df_copy.drop("last_payment_date", axis=1) # Exclude as this is determined after repayment of loan
df_copy = df_copy.drop("next_payment_date", axis=1) # Exclude since its a future information
df_copy = df_copy.drop("total_payment", axis=1) # Exclude since its just an outcome after a loan
df_copy = df_copy.drop("member_id", axis=1) # Exclude since its an identifier alone and not predictive
df_copy = df_copy.drop("sub_grade", axis=1) # Exclude as this is not required
df_copy = df_copy.drop("application_type", axis=1) # Exclude since we have just an application type


In [89]:
df_copy.describe(include="all")

,emp_length,home_ownership,loan_status,purpose,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc
count,38576,38576,38576,38576,38576,38576,3.857600e+04,38576.000000,38576.000000,38576.000000,38576.000000,38576.000000
unique,11,5,3,14,2,3,NaN,NaN,NaN,NaN,NaN,NaN
top,10+ years,RENT,Fully Paid,Debt consolidation,36 months,Not Verified,NaN,NaN,NaN,NaN,NaN,NaN
freq,8870,18439,32145,18214,28237,16464,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,6.964454e+04,0.133274,326.862965,0.120488,11296.066855,22.132544
std,NaN,NaN,NaN,NaN,NaN,NaN,6.429368e+04,0.066662,209.092000,0.037164,7460.746022,11.392282
min,NaN,NaN,NaN,NaN,NaN,NaN,4.000000e+03,0.000000,15.690000,0.054200,500.000000,2.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,4.150000e+04,0.082100,168.450000,0.093200,5500.000000,14.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,6.000000e+04,0.134200,283.045000,0.118600,10000.000000,20.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,8.320050e+04,0.185900,434.442500,0.145900,15000.000000,29.000000


In [90]:
# Let's check the dimension
df_copy.shape

(38576, 12)

In [91]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38576 entries, 0 to 38575
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   emp_length           38576 non-null  object 
 1   home_ownership       38576 non-null  object 
 2   loan_status          38576 non-null  object 
 3   purpose              38576 non-null  object 
 4   term                 38576 non-null  object 
 5   verification_status  38576 non-null  object 
 6   annual_income        38576 non-null  float64
 7   dti                  38576 non-null  float64
 8   installment          38576 non-null  float64
 9   int_rate             38576 non-null  float64
 10  loan_amount          38576 non-null  int64  
 11  total_acc            38576 non-null  int64  
dtypes: float64(4), int64(2), object(6)
memory usage: 3.5+ MB


### Check unique values to determine and fix inconsistencies

* Check for emp_length

In [92]:
# Check unique values in emp_length column
df_copy["emp_length"].unique()

array(['< 1 year', '9 years', '4 years', '10+ years', '3 years',
       '5 years', '1 year', '6 years', '2 years', '7 years', '8 years'],
      dtype=object)

In [93]:
# Let's remove the "years" at the back of the emp_length
#df_copy["emp_length"] = df_copy[ "emp_length"].str.replace('year', '', regex=False)

In [94]:
# Let's remove the "s" at the back of the emp_length
#df_copy["emp_length"] = df_copy[ "emp_length"].str.replace('s', '', regex=False)

In [116]:
# Let's see unique value again
#df_copy["emp_length"].unique()

In [96]:
# Let's change "10+" to "11"
df_copy["emp_length"] = df_copy["emp_length"].str.replace("10+", "11")

In [97]:
df_copy["emp_length"].unique()

array(['< 1 year', '9 years', '4 years', '11 years', '3 years', '5 years',
       '1 year', '6 years', '2 years', '7 years', '8 years'], dtype=object)

In [98]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38576 entries, 0 to 38575
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   emp_length           38576 non-null  object 
 1   home_ownership       38576 non-null  object 
 2   loan_status          38576 non-null  object 
 3   purpose              38576 non-null  object 
 4   term                 38576 non-null  object 
 5   verification_status  38576 non-null  object 
 6   annual_income        38576 non-null  float64
 7   dti                  38576 non-null  float64
 8   installment          38576 non-null  float64
 9   int_rate             38576 non-null  float64
 10  loan_amount          38576 non-null  int64  
 11  total_acc            38576 non-null  int64  
dtypes: float64(4), int64(2), object(6)
memory usage: 3.5+ MB


In [99]:
# Check unique values in home_ownership column
df_copy["home_ownership"].unique()

array(['RENT', 'MORTGAGE', 'OWN', 'OTHER', 'NONE'], dtype=object)

In [100]:
# Check unique values in purpose column
df_copy["purpose"].unique()

array(['car', 'credit card', 'Debt consolidation', 'educational',
       'home improvement', 'house', 'major purchase', 'medical', 'moving',
       'other', 'renewable_energy', 'small business', 'vacation',
       'wedding'], dtype=object)

In [101]:
# Check unique values in issue_date column
df_copy["term"].unique()

array([' 60 months', ' 36 months'], dtype=object)

In [102]:
# Check unique values in verification_status column
df_copy["verification_status"].unique()

array(['Source Verified', 'Not Verified', 'Verified'], dtype=object)

In [103]:
# Check unique values in annual_income column
df_copy["annual_income"].unique()

array([ 30000. ,  48000. ,  50000. , ...,  44250. ,  57040.5, 368000. ])

In [104]:
# Check unique values in dti column
df_copy["dti"].unique()

array([0.01  , 0.0535, 0.2088, ..., 0.2721, 0.2543, 0.272 ])

In [105]:
# Check unique values in dti column
df_copy["dti"].unique()

array([0.01  , 0.0535, 0.2088, ..., 0.2721, 0.2543, 0.272 ])

In [106]:
# Check unique values in int_rate column
df_copy["int_rate"].unique()

array([0.1527, 0.1864, 0.1596, 0.1065, 0.0603, 0.1465, 0.1427, 0.079 ,
       0.089 , 0.1269, 0.1242, 0.1171, 0.0991, 0.1629, 0.0743, 0.1114,
       0.1109, 0.0766, 0.0751, 0.0963, 0.0894, 0.1148, 0.1149, 0.157 ,
       0.0788, 0.0705, 0.1189, 0.1074, 0.1284, 0.0749, 0.0849, 0.1136,
       0.1199, 0.1095, 0.1099, 0.1221, 0.1241, 0.1134, 0.1399, 0.1367,
       0.1677, 0.1   , 0.0807, 0.0863, 0.0976, 0.1393, 0.0712, 0.1046,
       0.092 , 0.1166, 0.1091, 0.1103, 0.074 , 0.0768, 0.0662, 0.0599,
       0.0699, 0.0729, 0.0542, 0.0676, 0.0774, 0.0692, 0.0932, 0.0617,
       0.0639, 0.0579, 0.08  , 0.0859, 0.0714, 0.0691, 0.0737, 0.0832,
       0.0925, 0.1075, 0.0999, 0.1036, 0.1025, 0.1111, 0.1126, 0.1218,
       0.1059, 0.0962, 0.1037, 0.1158, 0.0988, 0.1062, 0.1253, 0.1051,
       0.1287, 0.1273, 0.138 , 0.1472, 0.1347, 0.1523, 0.1426, 0.1268,
       0.1311, 0.1417, 0.1349, 0.1304, 0.1599, 0.1595, 0.1533, 0.0654,
       0.1183, 0.1357, 0.1306, 0.1422, 0.1316, 0.1496, 0.1565, 0.1474,
      

In [107]:
# Check unique values in loan_amount column
df_copy["loan_amount"].unique()

array([ 2500,  3000, 12000,  4500,  3500,  8000,  6000,  5500, 24000,
        4125,  5400, 11200,  5000,  3050, 10000,  2225,  4000,  7000,
        9000,  4800,  6300,  4750,  1850,  4200,  7200,  2400,  7500,
        5550, 22000,  3200, 11000,  4400,  8500,  2000,  7400,  5650,
        1800,  6500, 15000,  8700,  5600,  4600,  3800, 16000,  1300,
        7800,  5900,  3600,  2100,  4975,  1925,  1500,  7750,  9600,
        3900, 12975,  5950,  5100,  5200,  1200,  4650,  1450,  3250,
        3300,  1700,  5525, 18000,  1750,  5375,  9500,  7600,  6400,
        9900,  1000, 10400, 23500, 22600, 23600, 13100,  5800, 10800,
        1900,  8400,  3075,  6200, 11500,  4350,  4150,  4900,  6125,
        2425,  1600,  7100,  8900, 14000, 12250,  3700, 17000,  2550,
        6250, 14400,  8200,  9250,  3375,  1675,  8600,  2800,  3525,
        8800,  2250,  4375,  1275,  5050, 25000,  9800,  6600,  8250,
        2825,  5975,  3350, 20000, 19000,  2200, 14750,  9575, 13250,
        2350, 10625,

In [108]:
# Check unique values in total_acc column
df_copy["total_acc"].unique()

array([ 4, 11,  9, 28, 30, 23, 31, 21, 33, 13,  3, 15, 18, 14,  8,  7, 20,
       39, 24, 10, 19, 27,  6, 16, 45, 25,  5, 43, 29, 22, 41, 35, 44, 36,
       17, 26, 37, 32, 47, 52, 42, 46, 12, 50, 34, 59, 38, 63, 49, 48, 61,
       51, 55, 40, 53, 62, 58, 67, 54, 57, 56, 70,  2, 64, 60, 80, 79, 71,
       66, 65, 69, 90, 68, 74, 75, 87, 78, 72, 77, 81, 76, 73])

* Fix Data Types

In [109]:
# Convert emp_length
#df_copy['emp_length'] = pd.to_numeric(df_copy['emp_length'], errors='coerce')


In [110]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38576 entries, 0 to 38575
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   emp_length           38576 non-null  object 
 1   home_ownership       38576 non-null  object 
 2   loan_status          38576 non-null  object 
 3   purpose              38576 non-null  object 
 4   term                 38576 non-null  object 
 5   verification_status  38576 non-null  object 
 6   annual_income        38576 non-null  float64
 7   dti                  38576 non-null  float64
 8   installment          38576 non-null  float64
 9   int_rate             38576 non-null  float64
 10  loan_amount          38576 non-null  int64  
 11  total_acc            38576 non-null  int64  
dtypes: float64(4), int64(2), object(6)
memory usage: 3.5+ MB


* Check for missing values

In [111]:
df_copy.isna().sum()

,0
emp_length,0
home_ownership,0
loan_status,0
purpose,0
term,0
verification_status,0
annual_income,0
dti,0
installment,0
int_rate,0


* To check for duplicates enteries

In [112]:
# Check for duplicates
print(df_copy.duplicated().sum())

0


### Check for Outliers

In [113]:
df_copy.describe()

,annual_income,dti,installment,int_rate,loan_amount,total_acc
count,3.857600e+04,38576.000000,38576.000000,38576.000000,38576.000000,38576.000000
mean,6.964454e+04,0.133274,326.862965,0.120488,11296.066855,22.132544
std,6.429368e+04,0.066662,209.092000,0.037164,7460.746022,11.392282
min,4.000000e+03,0.000000,15.690000,0.054200,500.000000,2.000000
25%,4.150000e+04,0.082100,168.450000,0.093200,5500.000000,14.000000
50%,6.000000e+04,0.134200,283.045000,0.118600,10000.000000,20.000000
75%,8.320050e+04,0.185900,434.442500,0.145900,15000.000000,29.000000
max,6.000000e+06,0.299900,1305.190000,0.245900,35000.000000,90.000000


### Save Cleaned Data

In [114]:
df_copy.to_csv("/content/mine_files/cleaned_data.csv", index=False)

In [115]:
df_copy.shape

(38576, 12)